//
//  OCNptResults.h
//  MDRCase
//
//  Created by CliffLeopard on 2022/5/30.
//

#ifndef OCNptResults_h
#define OCNptResults_h


#define OC_NPT_SUCCESS                     0
#define OC_NPT_FAILURE                     (-1)

#if !defined(OC_NPT_ERROR_BASE)
#define OC_NPT_ERROR_BASE -20000
#endif

// error bases
const int OC_NPT_ERROR_BASE_GENERAL        = OC_NPT_ERROR_BASE-0;
const int OC_NPT_ERROR_BASE_LIST           = OC_NPT_ERROR_BASE-100;
const int OC_NPT_ERROR_BASE_FILE           = OC_NPT_ERROR_BASE-200;
const int OC_NPT_ERROR_BASE_IO             = OC_NPT_ERROR_BASE-300;
const int OC_NPT_ERROR_BASE_SOCKET         = OC_NPT_ERROR_BASE-400;
const int OC_NPT_ERROR_BASE_INTERFACES     = OC_NPT_ERROR_BASE-500;
const int OC_NPT_ERROR_BASE_XML            = OC_NPT_ERROR_BASE-600;
const int OC_NPT_ERROR_BASE_UNIX           = OC_NPT_ERROR_BASE-700;
const int OC_NPT_ERROR_BASE_HTTP           = OC_NPT_ERROR_BASE-800;
const int OC_NPT_ERROR_BASE_THREADS        = OC_NPT_ERROR_BASE-900;
const int OC_NPT_ERROR_BASE_SERIAL_PORT    = OC_NPT_ERROR_BASE-1000;
const int OC_NPT_ERROR_BASE_TLS            = OC_NPT_ERROR_BASE-1100;

// general errors
const int OC_NPT_ERROR_INVALID_PARAMETERS  = OC_NPT_ERROR_BASE_GENERAL - 0;
const int OC_NPT_ERROR_PERMISSION_DENIED   = OC_NPT_ERROR_BASE_GENERAL - 1;
const int OC_NPT_ERROR_OUT_OF_MEMORY       = OC_NPT_ERROR_BASE_GENERAL - 2;
const int OC_NPT_ERROR_NO_SUCH_NAME        = OC_NPT_ERROR_BASE_GENERAL - 3;
const int OC_NPT_ERROR_NO_SUCH_PROPERTY    = OC_NPT_ERROR_BASE_GENERAL - 4;
const int OC_NPT_ERROR_NO_SUCH_ITEM        = OC_NPT_ERROR_BASE_GENERAL - 5;
const int OC_NPT_ERROR_NO_SUCH_CLASS       = OC_NPT_ERROR_BASE_GENERAL - 6;
const int OC_NPT_ERROR_OVERFLOW            = OC_NPT_ERROR_BASE_GENERAL - 7;
const int OC_NPT_ERROR_INTERNAL            = OC_NPT_ERROR_BASE_GENERAL - 8;
const int OC_NPT_ERROR_INVALID_STATE       = OC_NPT_ERROR_BASE_GENERAL - 9;
const int OC_NPT_ERROR_INVALID_FORMAT      = OC_NPT_ERROR_BASE_GENERAL - 10;
const int OC_NPT_ERROR_INVALID_SYNTAX      = OC_NPT_ERROR_BASE_GENERAL - 11;
const int OC_NPT_ERROR_NOT_IMPLEMENTED     = OC_NPT_ERROR_BASE_GENERAL - 12;
const int OC_NPT_ERROR_NOT_SUPPORTED       = OC_NPT_ERROR_BASE_GENERAL - 13;
const int OC_NPT_ERROR_TIMEOUT             = OC_NPT_ERROR_BASE_GENERAL - 14;
const int OC_NPT_ERROR_WOULD_BLOCK         = OC_NPT_ERROR_BASE_GENERAL - 15;
const int OC_NPT_ERROR_TERMINATED          = OC_NPT_ERROR_BASE_GENERAL - 16;
const int OC_NPT_ERROR_OUT_OF_RANGE        = OC_NPT_ERROR_BASE_GENERAL - 17;
const int OC_NPT_ERROR_OUT_OF_RESOURCES    = OC_NPT_ERROR_BASE_GENERAL - 18;
const int OC_NPT_ERROR_NOT_ENOUGH_SPACE    = OC_NPT_ERROR_BASE_GENERAL - 19;
const int OC_NPT_ERROR_INTERRUPTED         = OC_NPT_ERROR_BASE_GENERAL - 20;
const int OC_NPT_ERROR_CANCELLED           = OC_NPT_ERROR_BASE_GENERAL - 21;


const int OC_NPT_ERROR_BASE_ERRNO          = OC_NPT_ERROR_BASE-2000;
#define OC_NPT_ERROR_ERRNO(e)              (OC_NPT_ERROR_BASE_ERRNO - (e))


const char* OC_NPT_ResultText(int result);
#endif /* OCNptResults_h */
